### PR TITLE
chore: switch to search endpoint

### PR DESCRIPTION
**Pull request by Averethel**
The type search is now a protected endpoint requiring an API key. The endpoint that was on a catalogue service was only returning some dummy data.
I rephrased the challenge to be more in line with the search flow and provided links to APIs on the search service.
I also updated the screenshots to reflect the new text better.

### CODE REVIEW

**Review by lkappeler — APPROVED** [review]
Thanks for taking care!

**Comment by lkappeler** [comment]
@ufkaya In case there are some pending challenges you sent out, please make sure to let the candidates know about the change.

**Comment by Averethel** [comment]
I wouldn't change anything that had been sent out. That could derail the candidate unnecessarily. We're mainly interested in the implementation of make/model select and it doesn't matter that much which endpoint is called with the make/model selected.

**Comment by lkappeler** [comment]
Or like mention it. as it can be very confusing if you get the same results no matter what you send to no lose a lot of time in debugging something that returns dummy data...

**Pull request merged**
